const assert = require('node:assert/strict');
const fs = require('node:fs');
const setup = fs.readFileSync('Setup.js', 'utf8');
const code = fs.readFileSync('Code.js', 'utf8');
const html = fs.readFileSync('Index.html', 'utf8');

const sheets = ['Tickets','Clients','Categories','Users','TicketEvents','Settings','TicketSLACycles','ClientSizePriority','TicketIndex','SlackNotifications'];
const functions = ['ensureRuntimeSchema_','repairApplicationSchema','runSchemaMigrations_','ensureSheetSchema_','appendMissingColumns_','seedMissingConfigurationRows_','validateCompleteSchema_','getRequiredSheet_','validateApplicationSchema'];
sheets.forEach(name => assert(setup.includes(`'${name}'`), `central schema missing ${name}`));
functions.forEach(name => assert.match(setup, new RegExp(`function ${name}\\(`), `missing ${name}`));
assert.match(setup, /const CURRENT_SCHEMA_VERSION = 9;/);
assert.match(setup, /'Priority_Source','SLA_Source','Submission_Request_ID'/);
assert.match(setup, /'Priority','SLA_Hours','Active','Sort_Order'/);
assert.match(setup, /getSheets\(\).*getName/);
assert.match(setup, /tryLock\(3000\)/);
assert.match(setup, /finally \{ lock\.releaseLock\(\); \}/);
assert.match(setup, /setProperty\(APP_SCHEMA_VERSION_PROPERTY_, String\(CURRENT_SCHEMA_VERSION\)\)/);
assert(setup.indexOf('runSchemaMigrations_') < setup.lastIndexOf('setProperty(APP_SCHEMA_VERSION_PROPERTY_'));
assert.match(setup, /existing\.length \+ 1/); // append, never reorder
assert.doesNotMatch(setup, /deleteSheet\(|clearContents?\(.*Tickets/);
assert.match(setup, /Math\.min\(1000/);
assert.match(setup, /TICKET_INDEX_BACKFILL_NEXT_ROW/);
assert.match(setup, /newTrigger\('continueTicketIndexBackfill'\)/);
assert.match(code, /ensureRuntimeSchema_\(\);\s*const email/);
assert.match(code, /const sheet = getRequiredSheet_\(sheetName\)/);
assert.doesNotMatch(code, /throw new Error\(`Missing sheet:/);
assert.match(html, /SCHEMA_STARTUP_RETRIED/);
assert.match(html, /setTimeout\(requestInitialState,2000\)/);
assert.match(html, /Updating the application structure…/);
assert.equal((html.match(/setTimeout\(requestInitialState,2000\)/g)||[]).length, 1);
console.log('schema migration, self-healing, batching, and one-retry startup checks passed');
