const assert=require('assert'),fs=require('fs'),vm=require('vm');
const setup=fs.readFileSync('Setup.js','utf8'),code=fs.readFileSync('Code.js','utf8'),html=fs.readFileSync('Index.html','utf8');
function fn(source,name){const start=source.indexOf(`function ${name}(`);assert(start>=0,name);let brace=source.indexOf('{',start),depth=0;for(let i=brace;i<source.length;i++){if(source[i]==='{')depth++;else if(source[i]==='}'&&!--depth)return source.slice(start,i+1);}throw Error(name);}
const ctx={};vm.createContext(ctx);vm.runInContext(fn(setup,'simplifiedTaxonomyFields_'),ctx);
const matrix=[['API & Integration','API error'],['API & Integration','Webhook'],['Orders','Bulk upload'],['Tracking & Status','Status delayed'],['Labels & Documents','Barcode not scanning'],['Serviceability & Routing','Pincode issue'],['Reverse, RTO & QC','RTO issue'],['SF360 Portal','Page not loading'],['Shopify','Orders not fetched or imported'],['WooCommerce','Plugin connection or onboarding'],['Billing, COD & Bank','Invoice'],['Configuration Request','Enable service'],['Other','General support']];
for(const [group,name] of matrix){const x=ctx.simplifiedTaxonomyFields_(group,name);assert(x.fields.length<=4,`${group}/${name} has ${x.fields.length}`);assert(!x.fields.some(f=>['expected_result','actual_result','first_observed_at','impact_scope','environment','affected_count','affected_ids'].includes(f)));assert(!x.required.some(f=>['expected_result','actual_result','first_observed_at','impact_scope','environment','affected_count','affected_ids'].includes(f)));}
assert.deepStrictEqual(Array.from(ctx.simplifiedTaxonomyFields_('Other','General support').required),[]);
assert(!html.includes('class="progress-rail"'));assert(!html.includes('class="review-panel"'));assert(html.includes('Issue details / Paste the email here'));assert(html.includes('name="attachment"'));assert(html.includes('name="evidence_link"'));assert(html.includes("payload:form"));
assert(html.includes('Add more details'));assert(!/<textarea name="problemStatement"/.test(html));
assert(code.includes('problemStatement=cleanText_(form.problemStatement,5000)||businessCase'));
assert(html.includes('Object.entries(t.dynamicFields||{})'));
assert(setup.includes('function simplifyTicketForms()'));assert(setup.includes('customCategoriesPreserved'));assert(setup.includes('fromVersion < 9'));
const validateCtx={cleanText_:(v,n)=>String(v??'').trim().slice(0,n),safeJsonParse_:(v,f)=>{try{return JSON.parse(v)}catch{return f}},hasFile_:v=>!!v,fieldLabel_:x=>x,Error};vm.createContext(validateCtx);vm.runInContext(fn(code,'validateHttpUrl_')+'\n'+fn(code,'validateTicketForm_'),validateCtx);
const category=(group,name,fields,required)=>({Category_Group:group,Subcategory_Name:name,Category_Name:name,Fields_JSON:JSON.stringify(fields),Required_Fields_JSON:JSON.stringify(required)});
const base={emailSubject:'Subject',issueDescription:'Details',submissionRequestId:'request-1'};const regular={name:'Client',type:'Regular'};
assert.doesNotThrow(()=>validateCtx.validateTicketForm_({...base,expected_result:'old',actual_result:'old',first_observed_at:'old',impact_scope:'old',environment:'old',affected_count:'1',affected_ids:'old'},category('Other','General support',['attachment'],[]),regular));
assert.throws(()=>validateCtx.validateTicketForm_({...base},category('Orders','Order not created',['combined_identifier','attachment'],['combined_identifier']),regular),/AWB or Order ID/);
assert.throws(()=>validateCtx.validateTicketForm_({...base},category('Tracking & Status','Status delayed',['awb','status_details','attachment'],['awb']),regular),/AWB number/);
assert.throws(()=>validateCtx.validateTicketForm_({...base},category('API & Integration','API error',['endpoint','api_log','error_message','attachment'],['api_log']),regular),/API payload/);
assert.doesNotThrow(()=>validateCtx.validateTicketForm_({...base,evidence_link:'https://loom.com/share/example'},category('API & Integration','API error',['endpoint','api_log','error_message','attachment'],['api_log']),regular));
for(const group of ['Shopify','WooCommerce']){const id=group==='Shopify'?'shopify_identifier':'woocommerce_identifier';assert.throws(()=>validateCtx.validateTicketForm_({...base,store_url:'https://store.example'},category(group,'Integration',[ 'store_url',id,'error_message','attachment'],['store_url','attachment']),regular),/screenshot, file or video link/);assert.doesNotThrow(()=>validateCtx.validateTicketForm_({...base,store_url:'https://store.example',evidence_link:'https://drive.google.com/example'},category(group,'Integration',['store_url',id,'error_message','attachment'],['store_url','attachment']),regular));}
assert.throws(()=>validateCtx.validateTicketForm_({...base,evidence_link:'javascript:alert(1)'},category('Other','Other',['attachment'],[]),regular),/HTTP or HTTPS/);
assert.doesNotThrow(()=>validateCtx.validateTicketForm_({...base,evidence_link:'https://example.com/evidence'},category('Other','Other',['attachment'],[]),regular));
assert(code.includes("String(client.type) === '360'"));assert(code.includes('resolveTicketPriority_'));assert(code.includes('getSlaDuePreview'));
console.log('simplified ticket and feature request contracts passed');
